spring:
  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 1048253765@qq.com
    #QQ邮箱的授权码
    password: gjanuvswmwldbbce
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


#设置一个邮件发送人
lance:
  mail:
    sender: 1048253765@qq.com
server:
  port: 8083