#es:
#  host: 192.168.200.3
#  port: 9200
#  scheme: http
server:
  port: 8080
spring:
  data:
   elasticsearch:
     repositories:
       enabled: true
elasticsearch:
  host: 192.168.200.3
  port: 9200