server:
  port: 18082
spring:
  application:
    name: app-3song-order
eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.73:18080/eureka
    register-with-eureka: true
    fetch-registry: true
#ribbon的超时时间 ( SpringCloud feign客户端默认支持ribbon)
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
#hystrix的超时时间 开启断路器
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
