spring:
  rabbitmq:
  ####连接地址
    host: 127.0.0.1
   ####端口号   
    port: 5672
   ####账号 
    username: admin
   ####密码  
    password: 211716
   ### 地址
    virtual-host: /admin_host
    ###开启消息确认机制 confirms
    publisher-returns: true
    publisher-confirm-type: correlated
  #数据库连接信息
  datasource: 
        name: users
        url: jdbc:mysql://127.0.0.1:3306/itmayiedu-order?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
        username: root
        password: 211716
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver