###服务端口号
server:
  port: 18080
eureka:
  instance:
    #注册中心IP地址
    hostname: 192.168.50.73
  client:
    service-url:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #因为自己是注册中心，是否需要检索自己的服务信息
    fetch-registry: false
    #因为自己是注册中心，是否需要将自己注册给自己的注册中心（集群时需要为true）
    register-with-eureka: false

   # serviceUrl:
      #注册地址
     # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
